services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
  laravel:
    build:
      dockerfile: .
      context: ../
      target: frontend
