/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "api.auth.login": [],
    "api.auth.register": [],
    "api.auth.me": [],
    "api.auth.logout": [],
    "api.exercises.index": [],
    "api.exercises.store": [],
    "api.exercises.show": [
        {
            "name": "exercise",
            "required": true,
            "binding": "id"
        }
    ],
    "api.exercises.update": [
        {
            "name": "exercise",
            "required": true,
            "binding": "id"
        }
    ],
    "api.exercises.destroy": [
        {
            "name": "exercise",
            "required": true,
            "binding": "id"
        }
    ],
    "api.workouts.index": [],
    "api.workouts.store": [],
    "api.workouts.show": [
        {
            "name": "workout",
            "required": true
        }
    ],
    "api.workouts.update": [
        {
            "name": "workout",
            "required": true
        }
    ],
    "api.workouts.destroy": [
        {
            "name": "workout",
            "required": true
        }
    ],
    "api.schedules.index": [],
    "api.schedules.store": [],
    "api.schedules.show": [
        {
            "name": "schedule",
            "required": true,
            "binding": "id"
        }
    ],
    "api.schedules.update": [
        {
            "name": "schedule",
            "required": true,
            "binding": "id"
        }
    ],
    "api.schedules.destroy": [
        {
            "name": "schedule",
            "required": true,
            "binding": "id"
        }
    ],
    "login": [],
    "login.store": [],
    "register": [],
    "register.store": [],
    "logout": [],
    "dashboard.show": [],
    "exercises.create": [],
    "exercises.index": [],
    "exercises.store": [],
    "exercises.edit": [
        {
            "name": "exercise",
            "required": true,
            "binding": "id"
        }
    ],
    "exercises.update": [
        {
            "name": "exercise",
            "required": true,
            "binding": "id"
        }
    ],
    "exercises.destroy": [
        {
            "name": "exercise",
            "required": true,
            "binding": "id"
        }
    ],
    "homepage.show": [],
    "schedules.index": [],
    "schedules.show": [
        {
            "name": "schedule",
            "required": true,
            "binding": "id"
        }
    ],
    "schedules.destroy": [
        {
            "name": "schedule",
            "required": true,
            "binding": "id"
        }
    ],
    "schedules.mark-as-done": [
        {
            "name": "schedule",
            "required": true,
            "binding": "id"
        }
    ],
    "schedules.mark-as-missed": [
        {
            "name": "schedule",
            "required": true,
            "binding": "id"
        }
    ],
    "workouts.create": [],
    "workouts.index": [],
    "workouts.store": [],
    "workouts.edit": [
        {
            "name": "workout",
            "required": true,
            "binding": "id"
        }
    ],
    "workouts.update": [
        {
            "name": "workout",
            "required": true,
            "binding": "id"
        }
    ],
    "workouts.destroy": [
        {
            "name": "workout",
            "required": true,
            "binding": "id"
        }
    ]
}
}
export {};
