services:
  database:
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: main
  laravel-fpm:
    environment:
      APP_URL: "http://localhost"
      APP_ENV: staging
      APP_KEY: "base64:45Anb+KaWviZP0HXUKQSOdetU/jXt9Ue10LIy00Legk="
      JWT_SECRET: ""
      LOG_CHANNEL: stderr
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_DATABASE: main
      DB_USER: root
      DB_PASSWORD:
