volumes:
  frontend-build:

services:
  database:
    image: mariadb:10.11
  frontend:
    build:
      dockerfile: ./.docker/Dockerfile.frontend
      context: ..
    volumes:
      - type: volume
        source: frontend-build
        target: /app/public/build
        volume:
          subpath: .
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend-build:/var/www/html/public/build:ro
  laravel-fpm:
    build:
      dockerfile: ./.docker/Dockerfile
      context: ..
      target: laravel-fpm
    volumes:
      - frontend-build:/var/www/html/public/build:ro
    depends_on:
      - database
